# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

#Get the Jasypt Encryptor Password from the environment
jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD:}

# security configuration (this key should be unique for your application, and kept secret)
cloudopting.security.rememberme.key: e092330a3cdcf60699bf5128db337ead7e18f363
#spring.freemarker.checkTemplateLocation: true
#spring.freemarker.template-loader-path: classpath:/templates/
#spring.freemarker.templateLoaderPath: classpath:/templates/
#spring.freemarker.preferFileSystemAccess: false
async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    mail:
        baseUrl: http://cloudopting1.cloudapp.net
        protocol: smtp
        host: smtp.gmail.com
        port: 587
        username: cloudopting@gmail.com
        password: Smart@2012
        tls: true
        auth: true
        from: cloudopting@gmail.com

    messageSource:
        cacheSeconds: 1

swagger:
    title: cloudopting API
    description: cloudopting applications and beyond!
    termsOfServiceUrl: http://cloudopting.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
